### ISSUE TITLE
flipper-plugin-react-native-performance installation failure

### ISSUE THREAD

**Issue by ElviraBurchik** [Shopify/react-native-performance#83]
## Current behavior

@shopify/flipper-plugin-react-native-performance plugin fails to install with an error: 

```
Installation process of kind Install failed with: Error: ENOENT: no such file or directory, open '/var/folders/t7/3r8s1kl96_7bnd368nz4_0t00000gn/T/tmp-51806-WTB5Zxv2WO4A/@shopify__flipper-plugin-react-native-performance/package.json'
```

Most probably it happens because the package is prefixed with `@shopify` and flipper fails to find it. [More details in this issue](https://github.com/facebook/flipper/issues/3819). 

## Expected behavior

The package can be installed successfully.

## To Reproduce

Try to install plugin via Flipper UI. 

## Platform:
 - [ ] iOS
 - [ ] Android

## Packages
Which packages are affected by the issue?
- [ ] @shopify/react-native-performance
- [ ] @shopify/react-native-performance-lists-profiler
- [X] @shopify/flipper-plugin-react-native-performance
- [ ] @shopify/react-native-performance-navigation
- [ ] @shopify/react-native-performance-navigation-bottom-tabs
- [ ] @shopify/react-native-performance-navigation-drawer

## Environment

- [X] I've removed the packages that I don't use

| package                                                  | version         |
| -------------------------------------------------------- | --------------- |
| @shopify/flipper-plugin-react-native-performance         |1.0.1            |

**Comment by baveku** [comment]
> There is [an open PR with a naive solution](https://github.com/facebook/flipper/pull/3825), hopefully we get some feedback soon.
> 
> Until then this binary can be used directly: [flipper-plugin-react-native-performance-1.0.0.tgz.zip](https://github.com/Shopify/react-native-performance/files/8958538/flipper-plugin-react-native-performance-1.0.0.tgz.zip)

I can't install [flipper-plugin-react-native-performance-1.0.0.tgz.zip](https://github.com/Shopify/react-native-performance/files/8958538/flipper-plugin-react-native-performance-1.0.0.tgz.zip), it's wrong format when install to Flipper

**Comment by fortmarek** [comment]
Hey @baveku 👋 

Can you try with this archive instead: [flipper-plugin-react-native-performance-1.0.0.tgz](https://github.com/Shopify/react-native-performance/files/9100918/flipper-plugin-react-native-performance-1.0.0.tgz) ? We are still waiting on a response from the Flipper team to address this properly.

**Comment by baveku** [comment]
> Hey @baveku 👋
> 
> Can you try with this archive instead: [flipper-plugin-react-native-performance-1.0.0.tgz](https://github.com/Shopify/react-native-performance/files/9100918/flipper-plugin-react-native-performance-1.0.0.tgz) ? We are still waiting on a response from the Flipper team to address this properly.

thank you very much for the best plugin, I hope we can write more plugins like this
